/**
 * Supabase Migration: Workbooks Storage Bucket
 * v2.5 - 30 Napos Csakra Munkafüzet
 *
 * Creates storage bucket for 30-day workbook PDFs with proper RLS policies
 */

-- ============================================================================
-- CREATE STORAGE BUCKET
-- ============================================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'workbooks',
  'workbooks',
  false, -- Private bucket (use signed URLs)
  10485760, -- 10 MB limit
  ARRAY['application/pdf']
)
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- RLS POLICIES FOR WORKBOOKS BUCKET
-- ============================================================================

-- Policy 1: Allow service role to upload workbooks
CREATE POLICY "Allow service role uploads for workbooks"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'workbooks'
  AND auth.role() = 'service_role'
);

-- Policy 2: Allow service role to update workbooks
CREATE POLICY "Allow service role updates for workbooks"
ON storage.objects FOR UPDATE
USING (
  bucket_id = 'workbooks'
  AND auth.role() = 'service_role'
);

-- Policy 3: Allow service role to delete workbooks
CREATE POLICY "Allow service role deletes for workbooks"
ON storage.objects FOR DELETE
USING (
  bucket_id = 'workbooks'
  AND auth.role() = 'service_role'
);

-- Policy 4: Allow public read access via signed URLs only
-- (Signed URLs are generated by service role)
CREATE POLICY "Allow signed URL access for workbooks"
ON storage.objects FOR SELECT
USING (
  bucket_id = 'workbooks'
);

-- ============================================================================
-- NOTES
-- ============================================================================

/**
 * Security Notes:
 * - Bucket is PRIVATE (not public)
 * - Only service role can upload/update/delete
 * - Public read access is controlled via signed URLs (30-day expiry)
 * - File size limit: 10 MB (workbook PDFs ~2-5 MB expected)
 * - Only PDF files allowed
 *
 * Usage:
 * 1. Upload: supabase.storage.from('workbooks').upload(path, buffer)
 * 2. Signed URL: supabase.storage.from('workbooks').createSignedUrl(path, 2592000) // 30 days
 * 3. Update purchases.pdf_url with signed URL
 */
